var Data = [
    {
      
        title:'White kurta',
        pic:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzG9ntQu1LlmBEk0bDIwE6MveF1e9bnj_HJA&usqp=CAU",
        price:1500,
        type:'men',
        brand:"Alkaram Studio",
        color: "White",
    },

    {
        title:'White suit',
        pic:"https://medias.utsavfashion.com/media/catalog/product/cache/1/small_image/295x/040ec09b1e35df139433887a97daa66f/p/r/printed-cotton-flex-anarkali-suit-in-white-v1-kmm102.jpg",
        price:2500,
        type:'women',
        brand:"Khaadi",
        color: "white",
    },

    {
        title:'Black suit',
        pic:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPoAukGTgXIreeYk2UVyygLD3U7Umf_k5iFRCPmKAmCRh8v0msKHZsofrLVbrKzURCY6c&usqp=CAU",
        price:5000,
        type:'men',
        brand:"Bareeze",
        color: "Black",
    },

    {
        title:'White suit',
        pic:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCajBMRcGMx3PAPIH96UnXh28sDzY-wKe76g&usqp=CAU",
        price:2600,
        type:'women',
        brand:"Satrangi",
        color: "White",
    },

    {
        title:'Blue suit',
        pic:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6fwMUiAPh4CDd2l4Gv90Wee4BrkcM2xCy5qOoahhCiimzuP_Iv2mzWeygiVPbH_6RZF8&usqp=CAU",
        price:6000,
        type:'men',
        brand:"HSY Studio",
        color: "Blue",
    },

    {
        title:'Red suit',
        pic:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuo-ko6ccLcNb-JRLpfKcfdEWQiO-fkdYRAQ&usqp=CAU",
        price:2800,
        type:'women',
        brand:"ChenOne",
        color: "Red",
    },

    {
        title:'Gray salwar',
        pic:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQseSYjg9ghRnDW9rpRfkBuJLq2NTxCwEHKLjuu-e8fYgDvNOgVRr5bOso7wwyaUK8xhcA&usqp=CAU",
        price:1300,
        type:'men',
        brand:"Gul Ahmad",
        color: "Gray",
    },

    {
        title:'Red suit',
        pic:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYegFDTDrKrPSzYPLAv2E67lVj9HwLRNJH_-pIqRrxJLIRsqt5kuDkjyU1IJcTB5L_wGo&usqp=CAU",
        price:1800,
        type:'women',
        brand:"Junaid Jamshed",
        color: "Red",
    },

    {
        title:'Gray suit',
        pic:"https://i.pinimg.com/736x/75/f9/18/75f918a1b51c6723e7924778302b9fd6.jpg",
        price:5500,
        type:'men',
        brand:"Generation",
        color: "Gray",
    },

    {
        title:'Black suit',
        pic:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdp5wV3hz7ZNixqcEsCsc72BdSI1xbcBBV-ceDZk8CyJipQZmTBLjmk_Gd-TUeCQJKDgw&usqp=CAU",
        price:1400,
        type:'women',
        brand:"Nishat Linen",
        color: "Black",
    },

    {
        title:'Blue salwar',
        pic:"https://www.faisalabadfabricstore.com/wp-content/uploads/2019/07/SK-48-1-scaled.jpg",
        price:800,
        type:'men',
        brand:"Sapphire Retail",
        color: "Blue",
    },

    {
        title:'Black suit',
        pic:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKiD58Omx8lfbF_PJ68kiv8yDRsLTLZjtcoNeED0LSePoas7o6n8gIGev-JUUBb4wMkcw&usqp=CAU",
        price:1600,
        type:'women',
        brand:"zullbury",
        color: "Black",
    },

    {
        title:'Blue kurta',
        pic:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSpNrVl3wVPpda6s-0PWyCkg3U0XQ-8aqyHVlr1KsMRjBYb_qdvk0uT3DRl4l8hnDYdjZ0&usqp=CAU",
        price:1000,
        type:'men',
        brand:"maria B",
        color: "Blue",
    },

    {
        title:'Blue suit',
        pic:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQxmBZTg2bIDuvu9KJtsyMaFQDM5fAOh8m6SxycrD4_rtKVZjuh-o8qZPAG1Do6IK1zuo&usqp=CAU",
        price:2000,
        type:'women',
        brand:"Sana Sarfaraz",
        color: "Blue",
    },

    {
        title:'Black suit',
        pic:"https://pk.andreemilio.com/wp-content/uploads/2021/03/black-tuxedo-lapel-450x450.jpg",
        price:5400,
        type:'men',
        brand:"Zainab Chottani",
        color: "Black",
    },

    {
        title:'Blue suit',
        pic:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdQBcqaU7y_PL2MakzeukrU2D8UCt3IOZBbKqaKMHSeroDr9R4ypWD6ChGAM-gHeBnQLw&usqp=CAU",
        price:2200,
        type:'women',
        brand:"Hussain Rehar",
        color: "Blue",
    },

    {
        title:'White salwar',
        pic:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRlxR8WAuI4aKIITzOragZWYh5VZm8OdKCtg&usqp=CAU",
        price:1250,
        type:'men',
        brand:"Ali Xeeshan",
        color: "White",
    },

    {
        title:'Blue suit',
        pic:"https://c8.alamy.com/comp/2DCRK08/young-indian-woman-in-blue-salwar-kameez-looking-at-camera-smiling-happy-grey-background-2DCRK08.jpg",
        price:1700,
        type:'women',
        brand:"Asim Jofa",
        color: "Blue",
    },

    {
        title:'Black salwar',
        pic:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYMzI4cGXGnBuAOuHQLNG6TZgi_fvJQCSE1cIw2DaTfxH_eetN1Z3kMjZKduq9HfLqE_Y&usqp=CAU",
        price:1100,
        type:'men',
        brand:"Farah Talib Aziz",
        color: "Black",
    },
      {
        title:'Blue suit',
        pic:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSDqm-gsHyCxIpP8qoIrSscCo7XokYRWEqu_4gtW7PRdoHHguvTdt_85KoGV64AJYWq_7Q&usqp=CAU",
        price:900,
        type:'women',
        brand:"Cross Stitch",
        color: "Blue",
    },
      {
        title:'Gray kurta',
        pic:"https://www.thetimefashion.com/wp-content/uploads/2021/04/a.jpg",
        price:1450,
        type:'men',
        brand:"Zara Shahjahan",
        color: "Gray",
    },
       {
        title:'Black suit',
        pic:"https://i.ebayimg.com/images/g/ffcAAOSwDvBhuzsM/s-l500.jpg",
        price:1050,
        type:'women',
        brand:"Saira Shakira",
        color: "Black",
    },
       {
        title:'White suit',
        pic:"https://media1.popsugar-assets.com/files/thumbor/cwS3TtqvJM7G-mePAL6dn2yv9l8/0x442:3280x3722/fit-in/2048xorig/filters:format_auto-!!-:strip_icc-!!-/2022/09/12/085/n/1922564/ab6df6f4631fd6d12f0549.52401471_/i/white-suits-tuxedos-emmys-2022-red-carpet.jpg",
        price:4300,
        type:'men',
        brand:"Mushq",
        color: "White",
    },
       {
        title:'Red suit',
        pic:"https://assets0.mirraw.com/images/7334109/2884237__(1)_large_m.jpg?1567005584",
        price:2350,
        type:'women',
        brand:"Zaha",
        color: "Red",
    },
       { 
        title:'Black kurta',
        pic:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSw0VNu4SW0GxP1RFbOVXSHFTDMqSXyHtlZkA1ZfERIGkpnQvPkPik4UuKx4DTUxBSJIEE&usqp=CAU",
        price:1450,
        type:'men',
        brand:"Faiza Saqlain",
        color: "Black",
    },
       {
        title:'White suit',
        pic:"https://medias.utsavfashion.com/media/catalog/product/cache/1/small_image/295x/040ec09b1e35df139433887a97daa66f/e/m/embroidered-georgette-abaya-style-suit-in-off-white-v1-kch4913.jpg",
        price:2550,
        type:'women',
        brand:"LimeLight",
        color: "White",
    },
       {
        title: 'White suit',
        pic: "https://media.istockphoto.com/id/1161755450/photo/young-man-and-woman-isolated-over-gray-background.jpg?s=612x612&w=0&k=20&c=HVAM7j5dm65vXtmexWb_1uTeI_bQV44A2v0uPcrD77w=",
        price: 3000,
        type: 'man and women',
        brand:"Ego",
        color: "White",
    },
       {
       title: 'white suit',
       pic: "https://media.istockphoto.com/id/1189091313/photo/handsome-man-shopping-for-new-clothes-in-store.jpg?s=612x612&w=0&k=20&c=TxJ4B339e64K70sFgw3RU1xDsi7N0LDBZyT9pB29H64=",
       price: 35000,
       type: 'man',
       brand: "Ethnic",
       color: "White",
    },
       {
        title:'White kurta',
    pic:'https://sanaullastore.com/media/catalog/product/i/s/istor-men-kurta-eid-collection-2023-16-white-ist-70-_1_.jpg',
    price:2500,
    type:'men',
    brand:'Sanaulla Store',
    color:'White',
    },
      {
        title:'Purple kurta',
    pic:'https://assets2.andaazfashion.com/media/catalog/product/cache/1/image/a12781a7f2ccb3d663f7fd01e1bd2e4e/m/e/men-pakistani-wine-self-design-kurta-with-beige-pajama-for-eid-mkpv0443_1_1.jpg',
    price:2500,
    type:'men',
    brand:'Andaaz Fashion',
    color:'Purple',
    },
       {
        title:'White suite',
    pic:'https://www.opposuits.co.uk/media/catalog/product/cache/f85d11f19b66b7616a89c9dc40a49586/o/s/osui-0049_white_knight.jpg',
    price:6000,
    type:'men',
    brand:'OppoSuits',
    color:'White',
    },
       {
        title:'2 piece suite',
    pic:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbHxb_xwoSw9JeaVKEBEgyEErMcxqfx8PTYP1y4MYt_P85Lbzz',
    price:6800,
    type:'men',
    brand:'Pinterest',
    color:'Blue',
    },
       {
        title:'3 piece suite',
    pic:'https://i.etsystatic.com/19677262/r/il/e8da6e/4285242938/il_570xN.4285242938_k5o0.jpg',
    price:6500,
    type:'men',
    brand:'Etsy',
    color:'DarkBrown',
    },
       {
        title:'Bridemaid Dress',
    pic:'https://i.pinimg.com/1200x/a4/8f/82/a48f82aa6bf9ca23e9b37cb5291fafc0.jpg',
    price:35000,
    type:'women',
    brand:'Pinterest',
    color:'Blue',
    },
       {
        title:'Baggy pants',
    pic:'https://genie.pk/cdn/shop/files/MUZ08455_400x.png?v=1684135600',
    price:2500,
    type:'men',
    brand:'genie.pk',
    color:'Skyblue',
    },
       {
        title:'Baggy pants',
    pic:'https://freakins.com/cdn/shop/products/FreakinsMen-14.jpg?v=1680354087&width=1087',
    price:2500,
    type:'men',
    brand:'freakins',
    color:'Black',
    },
       {
        title:' Brown Cargo',
    pic:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8JL4Jc95wqp5U2KJ8-0GVBATSULgqZNJm0w&usqp=CAU',
    price:2500,
    type:'men',
    brand:'Ajio.com',
    color:'Brown',
    },     
       {
        title:'Fit Jeans',
    pic:'https://cdn.shopify.com/s/files/1/0553/1589/0291/files/skinny-min.jpg?v=1642056668',
    price:2000,
    type:'men',
    brand:'Montivo',
    color:'Blue',
    },
       {
        title:'light-Blue Denim ',
    pic:'https://img01.ztat.net/article/spp-media-p1/b2d533b7193b4e1b9f36076045e4730f/915b87a717d048868ce06e89fb2b4e00.jpg?imwidth=762',
    price:2500,
    type:'men',
    brand:'Zalando',
    color:'light-Blue',
    },
       {
        title:'Brown Cargo ',
    pic:'https://media.boohoo.com/i/boohooamplience/gzz64626_chocolate_xl.jpg?w=360&qlt=default&fmt=auto',
    price:3500,
    type:'women',
    brand:'Boohoo',
    color:'Brown',
    },
             {
        title:'White trouser ',
    pic:'https://rukminim2.flixcart.com/image/850/1000/ky3b0y80/trouser/f/g/u/15-16-years-213-bottam-original-imagaedt9n3gyxqr.jpeg?q=90',
    price:2000,
    type:'women',
    brand:'FlipKart',
    color:'White',
    },
       {
        title:'Wide Legs ',
    pic:'https://media.boohoo.com/i/boohoo/fzz45208_black_xl/female-black-tailored-strap-detail-wide-leg-pants/?w=900&qlt=default&fmt.jp2.qlt=70&fmt=auto&sm=fit',
    price:3500,
    type:'women',
    brand:'Boohoo',
    color:'Black',
    },
       {
        title:'Check Shirt ',
    pic:'https://assets.ajio.com/medias/sys_master/root/20220513/fDBt/627e2656f997dd03e2b9ee91/-473Wx593H-463480868-red-MODEL2.jpg',
    price:2500,
    type:'men',
    brand:'Ajio.com',
    color:'Red',
    },
       {
        title:'Check Shirt ',
    pic:'https://5.imimg.com/data5/SELLER/Default/2022/9/JK/SP/QT/64690889/check-black-and-white-full-sleeve-men-casual-cotton-shirt-500x500.jpeg',
    price:3000,
    type:'men',
    brand:'Daraz.pk',
    color:'Black & White',
    },
       {
        title:'Check Shirt ',
    pic:'https://assets.ajio.com/medias/sys_master/root/20230906/vVWa/64f80929afa4cf41f5b34d62/-473Wx593H-461119105-blue-MODEL.jpg',
    price:2000,
    type:'men',
    brand:'Ajio.com',
    color:'Blue',
    },
       {
        title:'Check Shirt ',
    pic:'https://assets.ajio.com/medias/sys_master/root/20220304/AhY4/62211b8caeb26921afc72cb6/-473Wx593H-469110557-orange-MODEL.jpg',
    price:2300,
    type:'men',
    brand:'Ajio.com',
    color:'Orange',
    },
       {
        title:'Check Shirt ',
    pic:'https://rukminim2.flixcart.com/image/850/1000/ks3jjbk0/shirt/w/h/y/s-sdn-big-yellow-check-u-turn-original-imag5qp4ra8udaaq.jpeg?q=90',
    price:2500,
    type:'men',
    brand:'FlipKart',
    color:'Yellow',
    }, 
       {
        title:'Check Shirt ',
    pic:'https://ae01.alicdn.com/kf/HTB1drZbIFXXXXXdXXXXq6xXFXXXZ.jpg_640x640Q90.jpg_.webp',
    price:2500,
    type:'women',
    brand:'AliExpress',
    color:'Blue',
    },
       {
        title:'Check Shirt ',
    pic:'https://m.media-amazon.com/images/I/71jNYxG1fJL._AC_UY580_.jpg',
    price:2400,
    type:'women',
    brand:'Amazon.ca',
    color:'Green',
    },
       {
        title:'Check Shirt ',
    pic:'https://rukminim2.flixcart.com/image/850/1000/xif0q/shirt/o/8/g/l-chek-shirt-women-022-j4u-original-imaghqzxsekdmgs2.jpeg?q=20',
    price:2700,
    type:'women',
    brand:'FlipKart',
    color:'Black & White',
    },
       {
        title:'Check Shirt ',
    pic:'https://m.media-amazon.com/images/I/517kFmfuYFL._QL92_SH45_SS200_.jpg',
    price:2500,
    type:'women',
    brand:'Amazone.com',
    color:'SkyBlue',
    },
       {
        title:'Check Shirt ',
    pic:'https://m.media-amazon.com/images/I/61JFUeJa0ZL._AC_SX466_.jpg',
    price:2500,
    type:'women',
    brand:'Amazone',
    color:'maroon',
    },
       {
        title:' Maxi-Dress ',
    pic:'https://999.com.pk/cdn/shop/products/76_6a644deb-d2ff-4c45-b156-22a058963bbc_800x.jpg?v=1624797950',
    price:6000,
    type:'women',
    brand:'Nine Ninety Nine',
    color:'D-Green',
    },
       {
    title:' Maxi-Dress ',
    pic:'https://www.jiomart.com/images/product/original/rveoqqgqhn/derifa-women-maroon-solid-viscose-maxi-dress-product-images-rveoqqgqhn-0-202212011103.jpg?im=Resize=(500,630)',
    price:6000,
    type:'women',
    brand:'JioMart',
    color:'Maroon',
    },
       {
        title:' Maxi-Dress ',
    pic:'https://images.bewakoof.com/t640/women-s-sleeveless-ethnic-dress-413676-1663921140-1.jpg',
    price:6000,
    type:'women',
    brand:'Beewakoof',
    color:'Hotpink',
    },
       {
        title:' Maxi-Dress ',
    pic:'https://images.prod.airrobe.link/images/listing_images/images/8449511/large/aere-9361-4140561-5.jpg?1691808494',
    price:6000,
    type:'women',
    brand:'AirRobe',
    color:'Black',
    },
       {
        title:' Maxi-Dress ',
    pic:'https://media.boohoo.com/i/boohoo/fzz40503_rust_xl_1/female-rust-plunge-wide-sleeve-maxi-dress',
    price:6000,
    type:'women',
    brand:'ASOS',
    color:'Orange',
    },
       {
        title:' Maxi-Dress ',
    pic:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwN0qOe54MCjscyl2QazG5gJjQ2cS3BuBcwwciNYSDnFWHN4V5APeAHgcz56JlT1XpvWY&usqp=CAU',
    price:6000,
    type:'women',
    brand:'Ajio.com',
    color:'Pinksky',
    },
       {
        title:' Graphic-Tee ',
    pic:'https://images.asos-media.com/products/columbia-rapid-ridge-back-graphic-t-shirt-in-white-exclusive-to-asos/204009633-1-white/?$n_480w$&wid=476&fit=constrain',
    price:3000,
    type:'men',
    brand:'ASOS',
    color:'White',
    },
       {
        title:' Graphic-Tee ',
    pic:'https://media.boohoo.com/i/boohoo/mzz89556_black_xl?w=900&qlt=default&fmt.jp2.qlt=70&fmt=auto&sm=fit',
    price:3000,
    type:'men',
    brand:'Boohoo',
    color:'Black',
    },
       {
        title:' Graphic-Tee ',
    pic:'https://i5.walmartimages.com/seo/Bonobos-Fielder-Men-s-and-Big-Men-s-Short-Sleeve-Relaxed-Graphic-Tee-Up-to-Size-3XL_2c3c8b4c-33e7-4123-aae4-55b97ea7c49e.11bf1476ed6f13843183e39feec7b15a.jpeg',
    price:3000,
    type:'men',
    brand:'Walmart',
    color:'D-Green',
    },
       {
        title:' Graphic-Tee ',
    pic:'https://www.beyoung.in/api/cache/catalog/products/printed_t-shirts_for_men_15_8_2022/definitely_not_yellow_t-shirt_for_men_base_15_6_2023_700x933.jpg',
    price:3000,
    type:'men',
    brand:'Beyoung',
    color:'yolk',
    },
       {
        title:' Graphic-Tee ',
    pic:'https://zellbury.com/media/catalog/product/z/e/zellbury-grey-pc-jersey-mgt22043-mwest-6_1.jpg',
    price:3000,
    type:'men',
    brand:'Zellbury',
    color:'Grey',
    },
    {
    title:'White Fabric Cotton',
    pic:'https://www.gulahmedshop.com/media/catalog/product/_/m/_m2a0459_8.jpg?optimize=medium&fit=bounds&height=&width=',
    price:4600,
    type:'men',
    brand:'Gul Ahmad',
    color:'White',
    },
    {
    title: 'White 3-pc Embroidered Lawn',
    pic:'//www.gulahmedshop.com/media/catalog/product/c/l/cl-375a_1_.jpg?optimize=medium&fit=bounds&height=&width=',
    price:2200,
    type:'Female',
    brand:'Gul Ahmad',
    color:'White',
   },
   {
   title: 'White Embroidered Kurta',
    pic:'https://www.gulahmedshop.com/media/catalog/product/w/h/white_embroidered_kurta_kr-emb23-020_3_.jpg?optimize=medium&fit=bounds&height=600&width=500',
    price:3900,
    type:'Male',
    brand:'Gul Ahmad',
    color:'White',
   },
{
    title: 'Fabric Cotton-LF',
    pic:'https://www.gulahmedshop.com/media/catalog/product/2/7/277054_1_.jpg?optimize=medium&fit=bounds&height=600&width=500',
    price:3700,
    type:'Male',
    brand:'Gul Ahmad',
    color:'Black',
 },  
 {
    title: 'Fabric Cotton-LF',
    pic:'https://www.gulahmedshop.com/media/catalog/product/3/6/366267_1_.jpg?optimize=medium&fit=bounds&height=600&width=500',
    price:2700,
    type:'Male',
    brand:'Gul Ahmad',
    color:'Mardi Gras',
 },  
 {
    title: 'Black & White Printed Lawn Suit',
    price:3900,
    type:'Female',
    brand:'Gul Ahmad',
    color:'Black & White',
 },
 {
    title: 'Black & White Printed Lawn suit',
    pic:'https://faisalfabrics.pk/cdn/shop/files/B-32028-1.jpg?v=1688887987',
    price:4100,
    type:'Female',
    brand:'Gul Ahmad',
    color:'Black & White',
 }, 
];
module.exports = Data;